# Generated by Django 5.0.4 on 2024-04-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=1000)),
                ('password_hash', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('firstname', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=1000)),
                ('token', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Income_Expenses',
            fields=[
                ('Table_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Table_name', models.CharField(max_length=1000)),
                ('Table_description', models.CharField(max_length=1000)),
                ('Table_shareKey', models.CharField(max_length=1000)),
                ('Table_edit', models.BooleanField(default=False)),
                ('Table_createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.user')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('Income_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Income_title', models.CharField(max_length=1000)),
                ('Income_cost', models.CharField(max_length=1000, null=True)),
                ('Income_datetime', models.DateTimeField()),
                ('Incomes_createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('Expenses_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Expenses_title', models.CharField(max_length=1000)),
                ('Expenses_cost', models.CharField(max_length=1000, null=True)),
                ('Expenses_datetime', models.DateTimeField()),
                ('Expenses_createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.user')),
            ],
        ),
    ]
