# Generated by Django 5.0.4 on 2024-04-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0003_summarytable_delete_table_income_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarytable',
            old_name='Table_shareKey',
            new_name='Table_path',
        ),
    ]
