# Generated by Django 5.0.4 on 2024-04-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0004_rename_table_sharekey_summarytable_table_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarytable',
            name='Table_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
