# Generated by Django 5.0.4 on 2024-04-12 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0005_alter_summarytable_table_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarytable',
            name='Table_Expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_views.expenses'),
        ),
        migrations.AlterField(
            model_name='summarytable',
            name='Table_Income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_views.income'),
        ),
    ]
