# Generated by Django 5.0.4 on 2024-04-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0006_alter_summarytable_table_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarytable',
            name='Table_Expenses',
        ),
        migrations.RemoveField(
            model_name='summarytable',
            name='Table_Income',
        ),
        migrations.CreateModel(
            name='groupIncomeExpenses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Expenses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.expenses')),
                ('Income_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.income')),
                ('Table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.summarytable')),
            ],
        ),
    ]
