# Generated by Django 5.0.4 on 2024-04-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0007_remove_summarytable_table_expenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupincomeexpenses',
            old_name='Expenses_id',
            new_name='Expenses',
        ),
        migrations.RenameField(
            model_name='groupincomeexpenses',
            old_name='Income_id',
            new_name='Income',
        ),
        migrations.RenameField(
            model_name='groupincomeexpenses',
            old_name='Table_id',
            new_name='Table',
        ),
    ]
