# Generated by Django 5.0.4 on 2024-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0008_rename_expenses_id_groupincomeexpenses_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Expenses_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='Income_cost',
            field=models.FloatField(null=True),
        ),
    ]
