# Generated by Django 5.0.4 on 2024-04-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0009_alter_expenses_expenses_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='Incomes_createBy',
            new_name='Income_createBy',
        ),
    ]
