# Generated by Django 5.0.4 on 2024-04-13 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0010_rename_incomes_createby_income_income_createby'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupExpenses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.expenses')),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.summarytable')),
            ],
        ),
        migrations.CreateModel(
            name='groupIncome',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.income')),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_views.summarytable')),
            ],
        ),
        migrations.DeleteModel(
            name='groupIncomeExpenses',
        ),
    ]
